---
title: "merging_datasets"
author: "Federico Chung"
date: "4/21/2020"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(naniar)
```

```{r}
demographic<-read.csv("FINALDemographic_Data.csv")
covid<-read.csv("states_cases_data.csv")
stayhome<-read.csv("quarantine.csv")
google<-read.csv("time_series_google.csv")

google<-
  google%>%
  mutate(Day=as.Date(Day))

day1<-as.Date("03/10/2020",format = "%m/%d/%Y")
day2<-as.Date("03/24/2020",format = "%m/%d/%Y")


google_timeseries<-
  google%>%
  filter(Day<=day2)%>%
  filter(Day>=day1)


```

```{r}
colnames(demographic)[2] <- "State"

colnames(covid)[2] <- "State"

stayhome<-stayhome %>% replace_with_na(replace = list(StayAtHome_date = "#N/A"))
no_na<-subset(stayhome,stayhome$StayAtHome_date!="NA") 
na<-stayhome%>%
    anti_join(no_na)%>%
    mutate(StayAtHome_date =as.Date(as.character(StayAtHome_date),format = "%m-%d-%Y"), na.rm = TRUE)
no_na1<-no_na%>%
  mutate(StayAtHome_date =as.Date(as.character(StayAtHome_date),format = "%m/%d/%Y"), na.rm = TRUE)
stayhomefinal<-rbind(no_na1,na)




covid<-covid%>%
  mutate(Day = as.Date(date, format = "%m/%d/%Y"))

colnames(covid)[2] <- "State"

covid%>%
  group_by(State)

google_timeseries<-google_timeseries%>%
  select(-c(X))



write.csv(all,"FinalDataSet.csv")
names(all)



time_series_final_Data<-google_timeseries%>%
  left_join(covid)%>%
  select(-c(date))%>%
  left_join(stayhome)%>%
  left_join(demographic)%>% 
  mutate(Region = ifelse(State %in% c("AK","CA","OR","WA","HI"), "West", ifelse(State %in% c("CO","UT","ID","MT","WY", "NM", "AZ", "NV"), "Mountain", ifelse(State %in% c("SD","ND","MN","KS","IN", "MI", "NE", "IA", "WI","IL", "OH", "MO", "OK"), "Midwest",  ifelse(State %in% c("TX","AL","MS","FL","AR", "WV", "TN", "NC", "SC","GA", "VA", "KY", "LA"), "South", ifelse(State %in% c("MD","PA","DE","NJ","NY", "MA", "CT", "NH", "VT","ME", "RI", "DC"), "Northeast", 0))))))

write.csv(time_series_final_Data,"time_series_final_Data.csv")
```

```{r}
colnames(lat_long)[2] <- "latitude"
names(lat_long)
```

```{r}
time_series_final_Data <- merge(time_series_final_Data,lat_long, by="State")
```


```{r}
Trump<- as.Date("03/16/2020", format = "%m/%d/%Y")

glimpse(time_series_final_Data)
time_series_final_Data%>%
  group_by(StateColor, Day)%>%
  mutate(mean_ChinaVirusInterest = mean(ChinaVirusInterest))%>%
  ggplot(aes(x = Day, y = mean_ChinaVirusInterest, color = StateColor))+
  geom_smooth(fill=NA)+
  geom_vline(xintercept = Trump)+
  geom_text(aes(Trump , 30, label = "Trump Tweets China Virus", vjust = -1), size = 3, color = "black")+
  scale_color_manual(values = c("#0000FF", "#800080", "#FF0000"))

```

