---
title: "Checkpoint 4"
author: "Will Madairy, Sofia Pozsonyiova, Quinn Rafferty, Federico Chung"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
header-includes:
  - \usepackage{tabularx}
output:
  pdf_document: default
  html_document: default
---

```{r, warning=FALSE, include=FALSE}
library(dplyr)
library(usmap)
library(maps)
library(ggplot2)
library(tidyverse)
library(ggmap)
library(viridis)
library(rgdal)
library(gridExtra)
library(plotly)
require(janitor)
require(reshape2)
require(tidyr)
require(rstan)
require(rstanarm)
require(bayesplot)
```


```{r}
Finaldata<-read.csv("time_series_final_Data.csv")
```

```{r} 
Finaldata <- Finaldata %>% select(-c(X)) 
Finaldata <- Finaldata %>% mutate(Day= as.Date(Day))
```

```{r}
Finaldata%>%
  mutate(perc_population_positive = positive/total_population)%>%
  group_by(State)%>%
  mutate(mean_corona_interest = mean(ChinaVirusInterest),
         max = max(ChinaVirusInterest),
         median = median(ChinaVirusInterest))%>%
  ggplot(aes(x = mean_corona_interest, y = perc_population_positive, color = percent_asian))+
  geom_point()+
  scale_colour_gradient2(low = "blue", mid = "lightblue", high = "red")
```

# Quinn plots stuff
```{r}
a<- ggplot(Finaldata, aes(x = ChinaVirusInterest, fill = as.factor(State))) + 
  geom_density(alpha = 0.5)+ ggtitle("China Virus Density by State")

b<- ggplot(Finaldata, aes(x = Day, y = ChinaVirusInterest, color = factor(State))) + 
    geom_point() + 
    geom_smooth(method = "lm", se = FALSE) + 
    facet_wrap(~ State) + 
    theme(legend.position = "right")+
    ggtitle("China Virus Interest by Day by State")

c<- ggplot(Finaldata, aes(x = ChinaVirusInterest, color = factor(StateColor))) + 
    geom_histogram() + 
    facet_wrap(~ Winner) +
    theme(legend.position = "right") + 
    scale_colour_manual( values=c("red"= "red3", "blue"= "royalblue", "purple"="darkorchid3")) +
    ggtitle("China Virus Google by State Poltical Party Winner")   

d <-  ggplot(Finaldata, aes(y=positive, x=Winner, fill=(Winner)))+
      geom_boxplot() +
      facet_wrap(~Region)+
      theme(legend.position = "none") +
      scale_fill_manual(values = c("Democrat"="blue3", "Republican"= "red3"))+
      lims(y= c(0,1000))+
      ggtitle("Positive COVID-19 Cases by State Political Party Winner & Region")

ggplotly(a)
ggplotly(b)
ggplotly(c) #Shows that Democrat states tend to have a higher interest in Googling China Virus 
ggplotly(d)

#################################### Notes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# What affects the China Interest search, is it demographic, policitical or COVID based? 
## From Alicia:: Start by thinking, take the four models from the sleep study and just think how we can go thorugh those four models in the context of our work. 

## Chosen variables: Number of COVID-19 cases, State color, percent black, percent white, income
```

#Quinn making models
```{r, cahce=TRUE}
set.seed(454)
Finaldata<-
  Finaldata%>%
  mutate(Day=as.numeric(Day))

model_1 <- stan_glmer(
  ChinaVirusInterest ~ (1 | State), #Gives us random intercepts
  data = Finaldata, family = gaussian, chains = 4, iter = 5000*2
)
```

```{r}
head(data.frame(summary(model_1)),-2)
```

#Quinn making models
```{r, warning=FALSE, cache=TRUE}
model_2 <- stan_glmer(
  ChinaVirusInterest ~ Day + (Day | State),
  data = Finaldata, family = gaussian,
  chains = 4, iter = 100, refresh = 0
)

```

```{r}
head(data.frame(summary(model_2)),-2)
```

#Quinn makes models
```{r, warning = FALSE, cache=TRUE}
model_3 <- stan_glmer(
  ChinaVirusInterest ~ Day + StateColor + (Day | State),#Random intercepts and slopes when we put Day in
  data = Finaldata, family = gaussian,
  chains = 4, iter = 100, refresh = 0
)
```

```{r}
head(data.frame(summary(model_3)),-2)
```

#Quinn makes models
```{r, warning = FALSE, cache=TRUE}
model_4 <- stan_glmer(
  ChinaVirusInterest ~ Day + totalTestResults + (Day | State),#Random intercepts and slopes when we put Day in
  data = Finaldata, family = gaussian,
  chains = 4, iter = 100, refresh = 0
)
```

```{r}
head(data.frame(summary(model_4)),-2)
```


```{r, warning = FALSE, cache=TRUE}
model_5 <- stan_glmer(
  ChinaVirusInterest ~ Day + totalTestResults + positive + percent_white +  (Day | State),#Random intercepts and slopes when we put Day in
  data = Finaldata, family = gaussian,
  chains = 4, iter = 100, refresh = 0
)
```

```{r}
head(data.frame(summary(model_5),-2))
```

