---
title: "BayesCap-Will"
author: "Will Madairy"
date: "4/21/2020"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(ggplot2)
```


```{r}
googledata<-read.csv("/Users/willmadairy/Documents/BayesData/Alaska.csv")
```
```{r}
write.csv(googledata, "/Users/willmadairy/Documents/BayesData/googlesearch.csv")
```

```{r}
google_ts<-read.csv("/Users/willmadairy/Documents/GitHub/COVID-19Bayes/Google/Time_series_Google.csv")
```

```{r}
google_ts_reg<-google_ts %>% 
  mutate(Region = ifelse(State %in% c("AK","CA","OR","WA","HI"), "West", ifelse(State %in% c("CO","UT","ID","MT","WY", "NM", "AZ", "NV"), "Mountain", ifelse(State %in% c("SD","ND","MN","KS","IN", "MI", "NE", "IA", "WI","IL", "OH", "MO", "OK"), "Midwest",  ifelse(State %in% c("TX","AL","MS","FL","AR", "WV", "TN", "NC", "SC","GA", "VA", "KY", "LA"), "South", ifelse(State %in% c("MD","PA","DE","NJ","NY", "MA", "CT", "NH", "VT","ME", "RI", "DC"), "Northeast", 0))))))
```


This set of data looks at the interest in 

```{r}
google_ts %>% 
  ggplot(aes(x=Day, y=ChinaVirusInterest, color=State)) + 
  geom_point()
```
```{r}
google<-google_ts_reg %>% 
  mutate(date = mdy(Day))
```


```{r}
google_ts_reg %>% 
  group_by(Region, Day) %>% 
  summarize(ChinaVirusSearch = median(ChinaVirusInterest)) %>% 
  ggplot(aes(x=Day, y=ChinaVirusSearch, color=Region))+
  geom_point()
```


